# Generated by Django 3.0.7 on 2025-02-06 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20250206_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='isLunch',
            field=models.BooleanField(default=False),
        ),
    ]
